import React from "react";
import { BrandLogo } from "../SearchAutoCompleteStyledComp/StyledComp";

export default function Brand({ size, color }) {
    return (
        <BrandLogo
            className="position-absolute"
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            x="0px"
            y="0px"
            width={size}
            height={size}
            viewBox="0 0 510 512"
            enable-background="new 0 0 510 512"
        >
            <g id="Layer_2">
                <path
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    d="M41.5,125.5v275c0,0,125-5,122-138
		S41.5,125.5,41.5,125.5z"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="41.5,262.5 163.5,262.5 184.5,262.5 	"
                />
                <path
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    d="M41.5,325.85c0,0,100.01,8.78,96.51,25.71"
                />
                <path
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    d="M41.5,196.4c0,0,92.94-5.83,92.97-23.87"
                />
                <path
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    d="M47.65,399.93c129.15-171.57,0-273.88,0-273.88"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="122.13,159.36 163.5,111.5 209.5,111.5 	
		"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="228.5"
                    cy="115.5"
                    r="19"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="344.5,89.5 281.5,89.5 247.07,111.5 	"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="359"
                    cy="89"
                    r="14.5"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="150.86,199.86 214.5,199.5 251.5,159.5 
		278.5,159.5 	"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="295.5"
                    cy="159.5"
                    r="19"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="160.37,231.32 271.5,227.5 295.5,199.5 
		335.5,199.5 	"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="347.5"
                    cy="199.5"
                    r="12"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="160.37,300.97 269.5,300.5 306.5,342.5 
		335.5,342.5 	"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="148.74,334.67 209.5,334.5 238.5,372.5 
		283.5,372.5 	"
                />
                <polyline
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    points="122.13,368.3 163.5,411.5 209.5,411.5 	
		"
                />
                <line
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    x1="247.5"
                    y1="411.5"
                    x2="327.5"
                    y2="411.5"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="200.5"
                    cy="263.5"
                    r="11"
                />
                <line
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    x1="211.5"
                    y1="263.5"
                    x2="344.5"
                    y2="263.5"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="367.5"
                    cy="263.5"
                    r="20"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="345.5"
                    cy="348.5"
                    r="14"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="295.5"
                    cy="372.5"
                    r="9"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="228.5"
                    cy="413.5"
                    r="21"
                />
                <circle
                    fill="none"
                    stroke={color}
                    strokeWidth="9"
                    strokeMiterlimit="10"
                    cx="341.5"
                    cy="411.5"
                    r="10"
                />
            </g>
        </BrandLogo>
    );
}
